name: Update chromeplus manifest

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-chromeplus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest release info
        id: get_release
        run: |
          response=$(curl -s https://api.github.com/repos/Bush2021/chrome_plus/releases/latest)
          echo "$response" > release_info.json
          tag_name=$(jq -r '.tag_name' release_info.json)
          asset_url=$(jq -r '.assets[0].browser_download_url' release_info.json)
          if [ -z "$tag_name" ] || [ -z "$asset_url" ]; then
            echo "Failed to fetch release info"
            exit 1
          fi
          echo "TAG_NAME=$tag_name" >> $GITHUB_ENV
          echo "ASSET_URL=$asset_url" >> $GITHUB_ENV

      - name: Check current manifest version
        id: get_current_version
        run: |
          current_version=$(jq -r '.version' bucket/chromeplus.json)
          echo "CURRENT_VERSION=$current_version" >> $GITHUB_ENV

      - name: Compare versions
        id: version_check
        run: |
          if [ "$TAG_NAME" = "$CURRENT_VERSION" ]; then
            echo "Versions match. No update needed."
            exit 0
          else
            echo "Versions do not match. Update needed."
          fi

      - name: Download latest release
        if: steps.version_check.outputs.result == 'false'
        run: |
          if [ -z "$ASSET_URL" ]; then
            echo "ASSET_URL is not set"
            exit 1
          fi
          curl -L -o chromeplus.7z "$ASSET_URL"
          sha256sum chromeplus.7z | awk '{ print $1 }' > hash.txt

      - name: Update manifest
        if: steps.version_check.outputs.result == 'false'
        run: |
          if [ ! -f bucket/chromeplus.json ]; then
            echo "bucket/chromeplus.json does not exist"
            exit 1
          fi
          version=${TAG_NAME#v}
          hash=$(cat hash.txt)
          jq ".version = \"$version\" | .architecture[\"64bit\"].url = \"$ASSET_URL\" | .architecture[\"64bit\"].hash = \"$hash\"" bucket/chromeplus.json > bucket/chromeplus_updated.json
          mv bucket/chromeplus_updated.json bucket/chromeplus.json

      - name: Commit and Push changes
        if: steps.version_check.outputs.result == 'false'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add bucket/chromeplus.json
          git commit -m 'Update chromeplus manifest'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
