name: Update chromeplus manifest

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-chromeplus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest release info
        id: get_release
        run: |
          response=$(curl -s https://api.github.com/repos/Bush2021/chrome_plus/releases/latest)
          echo "$response" > release_info.json
          tag_name=$(jq -r '.tag_name' release_info.json)
          asset_url=$(jq -r '.assets[0].browser_download_url' release_info.json)
          echo "TAG_NAME=$tag_name" >> $GITHUB_ENV
          echo "ASSET_URL=$asset_url" >> $GITHUB_ENV

      - name: Download latest release
        run: |
          curl -L -o chromeplus.7z "$ASSET_URL"
          sha256sum chromeplus.7z | awk '{ print $1 }' > hash.txt

      - name: Update manifest
        run: |
          version=${TAG_NAME#v}
          hash=$(cat hash.txt)
          jq ".version = \"$version\" | .architecture[\"64bit\"].url = \"$ASSET_URL\" | .architecture[\"64bit\"].hash = \"$hash\"" bucket/chromeplus_template.json > bucket/chromeplus.json

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add bucket/chromeplus.json
          git commit -m 'Update chromeplus manifest'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
